--create TABLE IN A CURRENT DATABASE

CREATE DATABASE IF NOT EXISTS hbtn_0c_0;


--create tables
CREATE TABLE IF NOT EXISTS first_table(
    id INT,
    name VARCHAR(256)
);

--DOES NOT FAIL IF TABLE EXIST
DO NOTHING;